-- 서브쿼리
SELECT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'MILK'
) AND NAME = 'YOGURT'
ORDER BY CART_ID

-- 셀프조인
SELECT C1.CART_ID
FROM CART_PRODUCTS C1, CART_PRODUCTS C2
WHERE C1.CART_ID = C2.CART_ID AND (C1.NAME = 'MILK' AND C2.NAME = 'YOGURT')
